server:
  port: 8010
spring:
  application:
    name: order
  datasource:
     url: jdbc:mysql://localhost:3306/springcloud-diancan?useUnicode=true
     password: chengyang
     username: root
     driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.cy.entity